// game/art/bitmap/index.ts — the bitmap-actor runtime (option C,
// .claude/prompts/bitmap-pipeline.md). HAND-WRITTEN: the types, the pose
// fallbacks, the decoder and the lookup live here; the DATA — BITMAP_ACTORS —
// is `./registry.ts`, GENERATED by `node tools/intake.mjs bitmap` from
// `./manifest.json` and never hand-edited. game/art/actors.ts consumes
// BITMAP_ACTORS / bitmapFor in bakePose, drawActor and actorHitRect; the art
// loop's tools (tools/lineup.ts) await loadBitmapActors before they measure.

import { BITMAP_ACTORS } from './registry';

export { BITMAP_ACTORS } from './registry';

export type PoseName = 'idle' | 'attack' | 'hurt' | 'cast' | 'dead';

export interface BitmapActor {
  readonly id: string;
  /** On-screen height in px, one bitmap px per screen px (ACTOR_SCALE-equivalent 1). */
  readonly height: number;
  /** Floor contact, in this actor's own bitmap px — bottom centre of the opaque mass. */
  readonly feet: { readonly x: number; readonly y: number };
  /** Torso centre, in bitmap px — targeting cursors, hit pops, the light-actor anchor. */
  readonly hit: { readonly x: number; readonly y: number };
  /** Torso box size, in bitmap px. */
  readonly hitSize: { readonly w: number; readonly h: number };
  /** Pose -> ordered frame URLs. A pose absent here falls back per POSE_FALLBACK below. */
  readonly poses: Partial<Record<PoseName, readonly string[]>>;
}

/**
 * A pose an actor has no frames for borrows another's, in this order
 * (DESIGN.md → Layered actors: attack → idle, cast → attack, hurt → idle,
 * dead → hurt), so a partially generated actor is playable at every stage.
 */
export const POSE_FALLBACK: Record<PoseName, readonly PoseName[]> = {
  idle: ['idle'],
  attack: ['attack', 'idle'],
  cast: ['cast', 'attack', 'idle'],
  hurt: ['hurt', 'idle'],
  dead: ['dead', 'hurt', 'idle'],
};

const decoded = new Map<string, HTMLImageElement>();
let loadPromise: Promise<void> | null = null;

function everyBitmapUrl(): string[] {
  const urls: string[] = [];
  for (const actor of Object.values(BITMAP_ACTORS)) {
    for (const arr of Object.values(actor.poses)) {
      if (!arr) continue;
      for (const url of arr) if (url) urls.push(url);
    }
  }
  return urls;
}

/**
 * Decodes every registered PNG once. Idempotent (a later call returns the
 * same in-flight/resolved promise) — call it as early as this module loads
 * and again anywhere that wants to be sure decoding has finished; a handful
 * of small PNGs decode well inside a single boot, so `bitmapFor` in
 * practice never has to report "not yet loaded".
 */
export function loadBitmapActors(): Promise<void> {
  if (loadPromise) return loadPromise;
  const urls = [...new Set(everyBitmapUrl())];
  loadPromise = Promise.all(
    urls.map(
      (url) =>
        new Promise<void>((resolveOne) => {
          const img = new Image();
          img.onload = () => {
            decoded.set(url, img);
            resolveOne();
          };
          img.onerror = () => resolveOne(); // a broken asset must not hang boot
          img.src = url;
        }),
    ),
  ).then(() => undefined);
  return loadPromise;
}

/**
 * The decoded frame for (id, pose, frame): missing poses fall back per
 * POSE_FALLBACK, and within whichever pose is actually used, a missing frame
 * index falls back to that pose's own frame 0 (idle frame 1 -> frame 0, and
 * generally). `undefined` if `id` has no bitmap, or before
 * `loadBitmapActors` has decoded that URL.
 */
export function bitmapFor(id: string, pose: PoseName, frame: number): HTMLImageElement | undefined {
  const actor = BITMAP_ACTORS[id];
  if (!actor) return undefined;
  for (const p of POSE_FALLBACK[pose]) {
    const arr = actor.poses[p];
    if (!arr || arr.length === 0) continue;
    const url = arr[frame] ?? arr[0];
    if (!url) continue;
    const img = decoded.get(url);
    if (img) return img;
  }
  return undefined;
}
