// game/art/bitmap/registry.ts — GENERATED by `node tools/intake.mjs bitmap`
// from game/art/bitmap/manifest.json. Do not hand-edit: the next intake
// overwrites this file. This is the DATA; the runtime (the types, the pose
// fallbacks, the decoder, `bitmapFor`) is the hand-written ./index.ts.

import type { BitmapActor } from './index';

const EMBER_IDLE_0 = new URL('./ember/idle-0.png', import.meta.url).href;

export const BITMAP_ACTORS: Record<string, BitmapActor> = {
  EMBER: {
    id: 'EMBER',
    height: 112,
    feet: { x: 30, y: 112 },
    hit: { x: 30, y: 56 },
    hitSize: { w: 36, h: 50 },
    poses: { idle: [EMBER_IDLE_0] },
  },
};
