// Ember Quest — sprite art. Every actor is authored at px 1 at its rendered
// size with a black keyline in the rows and 2-3 body tones; idles are two
// frames (breathe = one mid-torso row dropped, feet planted; float = 1-px hover).
import { makeSprite, PICO8 } from '../engine';
import type { Sprite } from '../engine';

// --- Sprite helpers ----------------------------------------------------------------
export type Anim = [Sprite, Sprite];
/**
 * 2-frame idle BREATHE for a grounded actor: frame B drops one mid-torso row
 * and pads the top, so the head/shoulders sink 1 px while the feet stay
 * planted — height and footprint are unchanged. Built once at setup.
 */
function breatheFrames(rows: string[], map: Record<string, string>): Anim {
  const w = rows[0].length;
  const cut = Math.round(rows.length * 0.55);
  const squashed = ['.'.repeat(w), ...rows.slice(0, cut), ...rows.slice(cut + 1)];
  return [makeSprite(rows, map), makeSprite(squashed, map)];
}
/** 2-frame idle FLOAT for a hovering actor: frame B lifts the whole body 1 px. */
function floatFrames(rows: string[], map: Record<string, string>): Anim {
  const w = rows[0].length;
  return [makeSprite(rows, map), makeSprite([...rows, '.'.repeat(w)], map)];
}

// --- Actor sprites (all authored at px 1, keyline in the rows, 2-3 body tones) ------
// HERO — 22x27 at px 1.
export const heroFrames = breatheFrames([
  '.......kpk............',
  '.......kpk............',
  '......kppk............',
  '......kppk..........k.',
  '.....kkhhkk........kwk',
  '....khhhbbbk.......kwk',
  '....khbbbbbsk.....kwgk',
  '....kbbbbbbsk.....kwgk',
  '....kbkeekbsk.....kwgk',
  '....kbbbbbbsk....kwgk.',
  '.....kbbbbsk.....kwgk.',
  '...kkkkbbbkkkk...kwgk.',
  '..khhhbbbbbbsskk.kwgk.',
  '.khhbbbbbbbbbssskhhhhk',
  '.kbbbkbbbbbbkbbsskhkk.',
  '.kbbsk.bbbb.kbbsskbk..',
  '.kssk.kbbbbk.kssskkk..',
  '.kkk..kbhbbk..kkkk....',
  '......kbbbbk..........',
  '......kbbsbk..........',
  '......kbbsbk..........',
  '......kbkkbk..........',
  '.....kbskksbk.........',
  '.....kbsk.ksk.........',
  '.....kssk.ksk.........',
  '....kbbbk.kbbbk.......',
  '....kkkkk.kkkkk.......',
], { k: PICO8[0], b: PICO8[8], s: PICO8[2], h: PICO8[9], p: PICO8[7], w: PICO8[6], g: PICO8[5], e: PICO8[10] });
// SLIME — 20x14 at px 1.
const slimeFrames = breatheFrames([
  '.......kkkkkk.......',
  '.....kkbbbbbbkk.....',
  '....kbbhhbbbbbbk....',
  '...kbbhbbbbbbbbbk...',
  '..kbbbbbbbbbbbbbsk..',
  '..kbbbkkbbbbkkbbsk..',
  '.kbbbbkhbbbbkhbbssk.',
  '.kbbbbbbbbbbbbbbssk.',
  '.kbbbbbbbbbbbbbsssk.',
  'kbbbbbbbbbbbbbbssssk',
  'kbbbbbbbbbbbbbsssssk',
  'ksbbbbbbbbbbbbsssssk',
  '.ksssbkksssssbkksssk',
  '..kkkk..kkkkk..kkkk.',
], { k: PICO8[0], b: PICO8[11], s: PICO8[3], h: PICO8[7] });
// GOBLIN — 18x20 at px 1.
const goblinFrames = breatheFrames([
  '..............kk..',
  '.............kcck.',
  '............kcwcck',
  '............kcccck',
  '.....kkkk....kcck.',
  '....kbbbbk....kak.',
  '...kbhbbbbk...kak.',
  '...kbebbebk..kak..',
  '...kbbbbbbk..kak..',
  '...kbtbbtbk..kak..',
  '....kbbbbbbkkkbk..',
  '...kbbbbbbbbbbbk..',
  '..kbbbbbbbbbbbbsk.',
  '..kbbkbbbbbbbkbsk.',
  '..kssk.bbbbb.kssk.',
  '..kkk.kbbbbbk.kkk.',
  '......kbbsbbk.....',
  '......kbkkkbk.....',
  '.....kssk.kssk....',
  '.....kkkk.kkkk....',
], { k: PICO8[0], b: PICO8[9], s: PICO8[4], h: PICO8[10], e: PICO8[8], t: PICO8[7], c: PICO8[5], w: PICO8[6], a: PICO8[4] });
// SKELETON — 14x26 at px 1.
const skeletonFrames = breatheFrames([
  '....kkkkkk....',
  '...kbbbbbbk...',
  '..kbbbbbbbbk..',
  '..kbkkbbkkbk..',
  '..kbkebbkebk..',
  '..kbbbbbbbbk..',
  '...kbkbbkbk...',
  '...kkkbskkk...',
  '.....kbsk.....',
  '..kkkkbbkkkk..',
  '.kbbbbbbbbbbk.',
  '.kbkbbsbbbkbk.',
  '.kbk.kbbk.kbk.',
  '.kbk.kkkk.kbk.',
  '.kbk.kbbk.kbk.',
  '.kbk.kkkk.kbk.',
  '.kskkbbbbkksk.',
  '.kk..kbsbk.kk.',
  '.....kbbsk....',
  '....kbkkbsk...',
  '....kbk.kbk...',
  '....kbk.kbk...',
  '....kbk.ksk...',
  '....ksk.ksk...',
  '...kbbk.kbbk..',
  '...kkkk.kkkk..',
], { k: PICO8[0], b: PICO8[7], s: PICO8[6], e: PICO8[8] });
// OGRE_KING — 30x34 at px 1.
const ogreKingFrames = breatheFrames([
  '..........kckckckck...........',
  '..........kcccccccck..........',
  '..........kcgccccgck..........',
  '.........kkbbbbbbbbkk.........',
  '........khbbbbbbbbbbsk........',
  '.......khbbbbbbbbbbbssk.......',
  '.......kbbbbbbbbbbbbssk.......',
  '.......kbkkbbbbbbkkbssk.......',
  '.......kbkebbbbbbkebssk.......',
  '.......kbbbbbbbbbbbbssk.......',
  '.......kbbbbkbbbbkbbssk.......',
  '.......kbbtbbbbbbbbtssk.......',
  '........kbtbbbbbbbbtsk........',
  '.........kkbbbbbbbbkk.........',
  '....kkkkkkkbbbbbbbbkkkkkkk....',
  '..kkhhbbbbbbbbbbbbbbbbbbsskk..',
  '.khhbbbbbbbbbbbbbbbbbbbbbsssk.',
  '.khbbbbbbbbbbbbbbbbbbbbbbsssk.',
  'khbbbbbkbbbbbbbbbbbbbbkbbssssk',
  'kbbbbbk.kbbbbbbbbbbbbk.kbssssk',
  'kbbbbbk.kbbbbbbbbbbbbk.kbssssk',
  'kbbbbk..kbbbbbbbbbbbbk..kssssk',
  'kbbbbk..kbbbbbbbbbbbbk..kssssk',
  'khbbbk..kbbbbbbbbbbbbk..ksssk.',
  'kkbbbk..kllllllllllllk..kssskk',
  '.kkkk...kllllllllllllk...kkkk.',
  '........klllkllllklllk........',
  '.........kbbbk..kbbbk.........',
  '.........kbbbk..kbbbk.........',
  '.........kbbsk..kbbsk.........',
  '.........kbbsk..kbbsk.........',
  '........kbbbbk..kbbbbk........',
  '........kbbbbkk.kbbbbkk.......',
  '........kkkkkkk.kkkkkkk.......',
], { k: PICO8[0], b: PICO8[4], s: PICO8[2], h: PICO8[15], c: PICO8[10], g: PICO8[8], e: PICO8[8], t: PICO8[7], l: PICO8[5] });
// WRAITH_LORD — 26x33 at px 1.
const wraithLordFrames = floatFrames([
  '..........kkkkkk..........',
  '........kkddddddkk........',
  '.......kddddddddddk.......',
  '......kddkkkkkkkkddk......',
  '......kdkkkkkkkkkkdk......',
  '......kdkkekkkkekkdk......',
  '......kdkkkkkkkkkkdk......',
  '......kddkkkkkkkkddk......',
  '.......kdddddddddsk.......',
  '....kkkkbbbbbbbbbbkkkk....',
  '..kkbbbbbbbbbbbbbbbbbbkk..',
  '.kbbbbbbbbbbbbbbbbbbbbbsk.',
  '.kbbbbkbbbbbbbbbbbbkbbbsk.',
  'kbbbbk.kbbbbbbbbbbbk.kbssk',
  'kbbbk..kbbbbbbbbbbbk..kssk',
  'kbbbk..kbbbbbbbbbbbk..kssk',
  'khhhk..kbbbbbbbbbbbk..khhk',
  '.kkk...kbbbbbbbbbbbk...kkk',
  '.......kbbbbbbbbbbsk......',
  '.......kbbbbbbbbbssk......',
  '.......kbbbbbbbbbssk......',
  '.......kbbbbbbbbsssk......',
  '......kbbbbbbbbbsssk......',
  '......kbbbbbbbbbsssk......',
  '......kbbbbkbbbbksssk.....',
  '......kbbbk.kbbbk.kssk....',
  '......kbbbk.kbbsk.kssk....',
  '.......kbk..kbsk..ksk.....',
  '.......kbk..kssk..ksk.....',
  '.......ksk..kssk...k......',
  '........k...ksk...........',
  '............ksk...........',
  '.............k............',
], { k: PICO8[0], b: PICO8[13], s: PICO8[2], d: PICO8[1], e: PICO8[14], h: PICO8[7] });
// DARK_LORD — 32x32 at px 1.
const darkLordFrames = breatheFrames([
  '..kk......................kk....',
  '.knnk....................knnk...',
  '.knnk....................knnk...',
  '..knnk..................knnk....',
  '..knnk......kkkkkk......knnk....',
  '...knnk...kkbbbbbbkk...knnk.....',
  '...knnkkkkbbbbbbbbbbkkkknnk.....',
  '....knnnbbbbbbbbbbbbbbnnnk......',
  '.....kkbbbbbbbbbbbbbbbbkk.......',
  '.......kbbkkkkkkkkkkbsk.........',
  '.......kbkkekkkkkkekksk.........',
  '.......kbbkkkkkkkkkkbsk.........',
  '........kbbbbbbbbbbssk..........',
  '.........kkbbbbbbbskk...........',
  '....kkkkkkkbbbgbbbkkkkkkkk......',
  '..kkbbbbbbbbbbgbbbbbbbbbsskk....',
  '.kccbbbbbbbbbbbbbbbbbbbbbsscck..',
  'kccckbbbbbbbbbbbbbbbbbbbskcccck.',
  'kccckbbbbkbbbbbbbbbbkbbbskcccck.',
  'kcccckbbk.kbbbbbbbbk.kbbkccccck.',
  'kcccckbbk.kbbhbbbbbk.ksskccccck.',
  'kcccck.k..kbbbbbbbbk..k.kccccck.',
  'kccccck...kbbbbbbbbk...kcccccck.',
  'kcccccck..kbbbbbbbsk..kccccccck.',
  'kccccccck.kbbbbbbbsk.kcccccccck.',
  'kccccccck.kkbbbbbskk.kcccccccck.',
  'kcccccccck.kbbkkbsk.kccccccccck.',
  'kcccccccck.kbbk.ksk.kccccccccck.',
  'kccccccccckkbsk.ksk.kccccccccck.',
  'kcccccccccckbsk.kskkcccccccccck.',
  'kccccccccccksk..kskcccccccccccck',
  '.kkkkkkkkkkkkk..kkkkkkkkkkkkkk..',
], { k: PICO8[0], b: PICO8[3], s: PICO8[1], h: PICO8[11], e: PICO8[8], n: PICO8[6], c: PICO8[2], g: PICO8[10] });
// ICE_WOLF — 38x16 at px 1.
const iceWolfFrames = breatheFrames([
  '..........kk......................k...',
  '........kkbbk....................kbk..',
  '.......kbbbbk...................kbbk..',
  '......kbkbbbkkkkkkkkkkkkkkkkkkkkbbbk..',
  '.....kbbebbbbbbbbbbbbbbbbbbbbbbbbbsk..',
  '....kbbbbbbbbbhhbbbbbbbbbbbbbbbbbssk..',
  '...kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbssk..',
  '..kbhkbbbbbbbbbbbbbbbbbbbbbbbbbbsssk..',
  '.kbhhkbbbbbbbbbbbbbbbbbbbbbbbbbbsssk..',
  '.kkkkkbbbbbbbbbbbbbbbbbbbbbbbbbssssk..',
  '.....kbbbkbbbbbbbbbbbbbkkbbbbbkbsssk..',
  '.....kbbk.kbbkkkkkkkkkbk.kbbbk.ksssk..',
  '.....kbsk.kbsk.......ksk.kbsk...kssk..',
  '.....kbsk.kbsk.......ksk.kssk...kssk..',
  '....kbbsk.kbbsk.....kbsk.kssk..ksssk..',
  '....kkkk..kkkkk.....kkkk.kkkk..kkkkk..',
], { k: PICO8[0], b: PICO8[12], s: PICO8[1], h: PICO8[7], e: PICO8[10] });
// ICE_BEAR — 28x18 at px 1.
const iceBearFrames = breatheFrames([
  '.........kkkkkkkkkkk........',
  '.......kkbbbbbbbbbbbkk......',
  '......kbbbbbbbbbbbbbbbk.....',
  '....kkbbbbbbbbbbbbbbbbbk....',
  '..kkbbbbbbbbbbbbbbbbbbbsk...',
  '.kbbbbbbbbbbbbbbbbbbbbbssk..',
  'kbkbbebbbbbbbbbbbbbbbbbsssk.',
  'kbbbbbbbbbbbbbbbbbbbbbbsssk.',
  'kbnbbbbbbbbbbbbbbbbbbbbsssk.',
  'kbnbbbbbbbbbbbbbbbbbbbbsssk.',
  '.kbbbbbbbbbbbbbbbbbbbbbsssk.',
  '.kkbbbbbbbbbbbbbbbbbbbbsssk.',
  '..kbbbbkbbbbbbbbbbbkbbbssk..',
  '..kbbbk.kbbbbbbbbbk.kbssbk..',
  '..kbbsk.kbbsk.kbbsk..kbssk..',
  '..kbbsk.kbbsk.kbbsk..kbssk..',
  '.kbbbsk.kbbsk.kbbsk.kbbssk..',
  '.kkkkkk.kkkkk.kkkkk.kkkkkk..',
], { k: PICO8[0], b: PICO8[7], s: PICO8[6], h: PICO8[7], e: PICO8[1], n: PICO8[5] });
// FROST_WISP — 20x19 at px 1.
const frostWispFrames = floatFrames([
  '.......kkkkkk.......',
  '.....kkbbbbbbkk.....',
  '....kbbhhbbbbbbk....',
  '...kbbhhhbbbbbbbk...',
  '..kbbhhbbbbbbbbbsk..',
  '..kbbhbbbbbbbbbbsk..',
  '.kbbbbbkbbbbkbbbssk.',
  '.kbbbbbkbbbbkbbbssk.',
  '.kbbbbbbbbbbbbbbssk.',
  '.kbbbbbbbbbbbbbsssk.',
  '..kbbbbbbbbbbbsssk..',
  '..kbbbbbbbbbbbsssk..',
  '...kbbbbbbbbbsssk...',
  '....kcbbbkbbbcsk....',
  '....kck.kcbk.kck....',
  '...kck..kck...kck...',
  '...kc...kc.....kck..',
  '..kc....k.......kc..',
  '..k..............k..',
], { k: PICO8[0], b: PICO8[12], s: PICO8[1], h: PICO8[7], c: PICO8[13] });
// YETI — 33x32 at px 1.
const yetiFrames = breatheFrames([
  '......kk.................kk......',
  '.....knnk...............knnk.....',
  '.....knnkk.kkkkkkkkkk..kknnk.....',
  '......knnkkbbbbbbbbbbkkknnk......',
  '.......knbbbbbbbbbbbbbbnnk.......',
  '........kbbhbbbbbbbbbbbsk........',
  '........kbhbkkkkkkkkbbbsk........',
  '........kbbkffffffffkbssk........',
  '........kbbkfkefkefkkbssk........',
  '........kbbkffffffffkbssk........',
  '........kbbkfffkkfffkbssk........',
  '.........kbkkffffffkkbsk.........',
  '.........kbbbkkkkkkbbbsk.........',
  '..kkkkkkkkkbbbbbbbbbbbsskkkkkkk..',
  '.kbbbbbbbbbbbbbbbbbbbbbbbbbbbbsk.',
  'khbbbbbbbbbbbbbbbbbbbbbbbbbbbbssk',
  'khbbbbbbbbbbbbbbbbbbbbbbbbbbbbssk',
  'kbbbbbbbkbbbbbbbbbbbbbbbbkbbbsssk',
  'kbbbbbbk.kbbbbbbbbbbbbbbk.kbssssk',
  'kbbbbbbk.kbbbbbbbbbbbbbbk.kbssssk',
  'kbbbbbk..kbbbbbbbbbbbbbbk..kssssk',
  'kbbbbbk..kbbbbbbbbbbbbbbk..kssssk',
  'kbhhbbk..kbbbbbbbbbbbbbsk..kbhhsk',
  'kkkkkk...kbbbbbbbbbbbbbsk...kkkkk',
  '.........kbbbbbbbbbbbbssk........',
  '.........kkbbbbbbbbbbsskk........',
  '..........kbbbbkkkkbbsk..........',
  '..........kbbbbk..kbssk..........',
  '..........kbbbbk..kbssk..........',
  '.........kbbbbbk..kbbssk.........',
  '.........kbbbbbkk.kbbsskk........',
  '.........kkkkkkkk.kkkkkkk........',
], { k: PICO8[0], b: PICO8[6], s: PICO8[13], h: PICO8[7], e: PICO8[8], f: PICO8[12], n: PICO8[15] });
// SANDWORM — 22x25 at px 1.
const sandwormFrames = breatheFrames([
  '.....kkkkkkkkk........',
  '....kbbbbbbbbbk.......',
  '...kbbbbbbbbbbbk......',
  '..kbbkkkkkkkkkbbk.....',
  '..kbkmmmmmmmmmkbk.....',
  '..kbkmhmhmhmhmkbk.....',
  '..kbkmmmmmmmmmkbk.....',
  '..kbkhmhmhmhmhkbk.....',
  '..kbbkkkkkkkkkbsk.....',
  '..krrrrrrrrrrrrrk.....',
  '..kbbbbbbbbbbbbssk....',
  '..kbbbbbbbbbbbbssk....',
  '..krrrrrrrrrrrrrsk....',
  '..kbbbbbbbbbbbbssk....',
  '...kbbbbbbbbbbbssk....',
  '...krrrrrrrrrrrrsk....',
  '...kbbbbbbbbbbbbsk....',
  '....kbbbbbbbbbbbssk...',
  '....krrrrrrrrrrrrsk...',
  '....kbbbbbbbbbbbbssk..',
  '.....kbbbbbbbbbbbssk..',
  'kkkkkkkrrrrrrrrrrrssk.',
  'kbbbbbbbbbbbbbbbbbsssk',
  'kssbbbbbbbbbbbbbbssssk',
  '.kkkkkkkkkkkkkkkkkkkkk',
], { k: PICO8[0], b: PICO8[15], s: PICO8[4], h: PICO8[7], r: PICO8[9], m: PICO8[2] });
// SCORPION — 30x19 at px 1.
const scorpionFrames = breatheFrames([
  '..........................kk..',
  '.........................ktk..',
  '........................kttk..',
  '.......................kbbk...',
  '......................kbbk....',
  '.kk..................kbbk.....',
  'kbbk.....kk.........kbsk......',
  'kbhbk...kbbk.......kbsk.......',
  'kbbbbk.kbhbk......kbsk........',
  '.kbbbbkkbbbbk....kbsk.........',
  '..kbbbbkkbbbk...kbsk..........',
  '...kbbkkkkbk..kkbsk...........',
  '....kkbbbbbkkkkbssk...........',
  '....kbebbbbbbbbbbssk..........',
  '...kbbbbbbbbbbbbbsssk.........',
  '..kbbbbbbbbbbbbbbssssk........',
  '..kbbkbbkbbkbbkbbkbbsk........',
  '.kbsk.ksk.ksk.ksk.kssk........',
  '.kkk..kkk.kkk.kkk.kkkk........',
], { k: PICO8[0], b: PICO8[10], s: PICO8[9], h: PICO8[7], e: PICO8[8], t: PICO8[8] });
// MUMMY — 16x25 at px 1.
const mummyFrames = breatheFrames([
  '.....kkkkkk.....',
  '....kbbbbbbk....',
  '...kbbxbbbbbk...',
  '...kbxxbkkbbk...',
  '...kbbbbkebsk...',
  '...kbbxbbbbsk...',
  '....kbbbbxsk....',
  '..kkkkbxbkkkkk..',
  '.kbbbbbbbbbbbbk.',
  'kbxbbkbbxbbkbbbk',
  'kbbxk.kbbbk.kxsk',
  'kbbbk.kxbbk.kbsk',
  'kbxsk.kbbxk.kbsk',
  'kbbsk.kbbbk.kxsk',
  'kxbsk.kbxbk.kbsk',
  'kbbsk.kbbbk.kbsk',
  '.kkk..kxbbk..kkk',
  '......kbbxk.....',
  '......kbkbk.....',
  '.....kbskbsk....',
  '.....kbskxsk....',
  '.....kxskbsk....',
  '.....kbskbsk....',
  '....kbbskbbsk...',
  '....kkkkkkkkk...',
], { k: PICO8[0], b: PICO8[6], s: PICO8[13], x: PICO8[4], e: PICO8[8] });
// SAND_GOLEM — 32x31 at px 1.
const sandGolemFrames = breatheFrames([
  '.........kkkkkkkkkkkk...........',
  '.........khhbbbbbbbsk...........',
  '.........khbbbbbbbbsk...........',
  '.........kbkkkbbkkksk...........',
  '.........kbkekbbkeksk...........',
  '.........kbkkkbbkkksk...........',
  '.........kbbbbcbbbbsk...........',
  '.........kkkkkkkkkkkk...........',
  '..kkkkkkkkkkkkkkkkkkkkkkkkkk....',
  '..khhhbbbbbbbbbbbbbbbbbbbbsk....',
  '..khbbbbbbbbbbbbbbbbbbbbbssk....',
  '..kbbbbbcbbbbbbbbbbbbbbbbssk....',
  '..kbbbbbbbbbbbbbccbbbbbbbssk....',
  '..kbbbbbbbbbbbbbbbbbbbbbbssk....',
  '..kkkkkkkkkbbbbbbbbbbkkkkkkk....',
  'kkkkkkk..kbbbbbbbbbbbsk..kkkkkkk',
  'khhbbsk..kbbbbbbbbbbbsk..khbbssk',
  'khbbbsk..kbbbcbbbbbbbsk..kbbbssk',
  'kbbbbsk..kbbbbbbbbbbbsk..kbbbssk',
  'kbbbbsk..kbbbbbbbbcbbsk..kbbbssk',
  'kbbbbsk..kbbbbbbbbbbbsk..kbbbssk',
  'kkkkkkk..kkkkkkkkkkkkkk..kkkkkkk',
  '.........kkkkkkkkkkkkkk.........',
  '.........khbbbskkhbbbsk.........',
  '.........kbbbbskkbbbbsk.........',
  '.........kbcbbskkbbbbsk.........',
  '.........kbbbbskkbbcbsk.........',
  '.........kbbbbskkbbbbsk.........',
  '........kkbbbbskkbbbbskk........',
  '........khbbbbsskbbbbbsk........',
  '........kkkkkkkkkkkkkkkk........',
], { k: PICO8[0], b: PICO8[4], s: PICO8[2], h: PICO8[9], e: PICO8[10], c: PICO8[5] });
// GUARDIAN — 25x27 at px 1.
const guardianFrames = breatheFrames([
  '.....................kk..',
  '....................kwwk.',
  '...................kwwwwk',
  '...................kwwwck',
  '........kkkkk......kwwwck',
  '.......khbbbsk.....kwwwck',
  '......khbbbbbsk.....kwwk.',
  '......kbkkkkksk......kak.',
  '......kbkekekbk......kak.',
  '......kbkkkkksk......kak.',
  '......kbbbbbbsk......kak.',
  '.......kbbbbsk.......kak.',
  '....kkkkkbbbkkkkk....kak.',
  '...khhbbbbbbbbbbsk...kak.',
  '..khbbbbbbbbbbbbbsk..kak.',
  '..kbbbkbbbbbbbbkbbskkkak.',
  '..kbbk.kbbbhbbbk.kbbbbak.',
  '..kbbk.kbbbbbbbk.kbsskak.',
  '..kbsk.kbbbbbbbk.kkkkkak.',
  '..kkk..kbbbbbbsk.....kak.',
  '.......kbbbbbbsk.....kak.',
  '.......kbbkkbbsk.....kak.',
  '.......kbbk.kbsk.....kkk.',
  '.......kbbk.kbsk.........',
  '.......kbsk.kbsk.........',
  '......kbbbk.kbbsk........',
  '......kkkkk.kkkkk........',
], { k: PICO8[0], b: PICO8[10], s: PICO8[9], h: PICO8[7], e: PICO8[12], w: PICO8[6], a: PICO8[4], c: PICO8[7] });
// ORACLE — 24x27 at px 1.
const oracleFrames = breatheFrames([
  '...................kk...',
  '..................kook..',
  '.................kohook.',
  '.................koook..',
  '.....kkkkk........kak...',
  '....kbbbbbk.......kak...',
  '...kbbbbbbbk......kak...',
  '...kbkffffbk......kak...',
  '...kbkfefefk......kak...',
  '...kbkffffbk......kak...',
  '...kbbkffkbk......kak...',
  '....kbbbbbsk......kak...',
  '..kkkkbbbbkkkk....kak...',
  '.khhbbbbbbbbbbk...kak...',
  '.khbbbbbbbbbbbsk..kak...',
  '.kbbbkbbbbbbbkbskkkak...',
  '.kbbk.kbbbbbbk.kbbbak...',
  '.kbsk.kbbbbbbsk.kbbak...',
  '.kkk..kbbbbbbsk.kkkkk...',
  '......kbbbbbbsk.........',
  '......kbbbbbbsk.........',
  '.....kbbbbbbbssk........',
  '.....kbbbbbbbssk........',
  '....kbbbbbbbbsssk.......',
  '....kbbbbbbbbsssk.......',
  '...kbbbbbbbbbssssk......',
  '...kkkkkkkkkkkkkkk......',
], { k: PICO8[0], b: PICO8[13], s: PICO8[2], h: PICO8[7], f: PICO8[15], e: PICO8[1], o: PICO8[12], a: PICO8[4] });
// PALADIN — 22x25 at px 1.
const paladinFrames = breatheFrames([
  'kk..................kk',
  'kwk......kkkkk.....kwk',
  'kwwk....khbbbsk...kwwk',
  'kwwwk...kbbbbbsk.kwwwk',
  'kwwwk...kbkkkksk.kwwwk',
  'kwwwwk..kbkekesk.kwwwk',
  'kwwwwk..kbkkkksk.kwwwk',
  'kwwwwk...kbbbbskkwwwwk',
  'kwwwwwkkkkbbbkkkwwwwwk',
  'kwwwwbbbbbbbbbbbbwwwwk',
  '.kwwkbbbbbbbbbbbbkwwk.',
  '.kwkbbbbkbbbbbbbbbkwk.',
  '..kkbbbk.kbbbbbbbbbkk.',
  '..kddddkkkbbbhbbbbbbk.',
  '.kddcddddkbbbbbbbbbbsk',
  '.kddcddddkbbbbbbbbbsk.',
  '.kdcccdddkbbbbbbbbbsk.',
  '.kddcddddkbbbbbbbbbsk.',
  '.kddcdddsk.kbbbbbbsk..',
  '..kdddddk..kbbkkbbsk..',
  '...kdddk...kbbk.kbsk..',
  '....kkk....kbbk.kbsk..',
  '...........kbsk.kbsk..',
  '..........kbbbk.kbbsk.',
  '..........kkkkk.kkkkk.',
], { k: PICO8[0], b: PICO8[7], s: PICO8[6], h: PICO8[10], e: PICO8[12], w: PICO8[15], d: PICO8[12], c: PICO8[10] });
// SERAPH — 39x33 at px 1.
const seraphFrames = floatFrames([
  '...............kgggggggk...............',
  '..............kgkkkkkkkgk..............',
  '...............kkkkkkkkk...............',
  '.kk..............kkkkk..............kk.',
  'kwwk............kbbbbbk............kwwk',
  'kwwwk...........kbbbbbk...........kwwwk',
  'kwwwwk..........kbkkkbk..........kwwwwk',
  'kwwwwwk.........kfkekfk.........kwwwwwk',
  'kwwwwwwk........kfffffk........kwwwwwwk',
  'kwwwwwwwk.......kkfffkk.......kwwwwwwwk',
  'kwwwwwwwwk...kkkkkbbbkkkkk...kwwwwwwwwk',
  'kwwwwwwwwwk.kbbbbbbbbbbbbbk.kwwwwwwwwwk',
  'kwwwwwwwwwwkkbbbbbbbgbbbbbkkwwwwwwwwwwk',
  'kwwwwwwwwwwwkbbbbkbgbgkbbbkwwwwwwwwwwwk',
  'kwwwwwwwwwwwkbbbk.kbgbk.kbkwwwwwwwwwwwk',
  'kwwwwwwwwwwwkbbbk.kbbbk.kbkwwwwwwwwwwwk',
  'kwwwwwwwwwwkkbffk.kbbbk.kffkkwwwwwwwwwk',
  'kwwwwwwwwwsk.kkk.kbbbbbk.kkk.kswwwwwwwk',
  'kwwwwwwwwssk.....kbbbbbk.....kssswwwwwk',
  'kwwwwwwwssk......kbbbbbk......ksssswwwk',
  'kwwwwwwssk.......kbbbbbk.......kssssswk',
  'kwwwwwssk........kbbbbbsk.......ksssssk',
  'kwwwwssk.........kbbbbbsk........kssssk',
  'kwwsssk.........kbbbbbbsk.........ksssk',
  'kssssk..........kbbbbbbsk..........kssk',
  'kssk............kbbbbbbssk..........kkk',
  'kk.............kbbbbbbbssk.............',
  'k..............kbgbbbbgssk.............',
  '...............kbbbbbbbsssk............',
  '..............kbbbbbbbbsssk............',
  '..............kbbbbbbbbsssk............',
  '.............kbbbbbbbbbssssk...........',
  '.............kkkkkkkkkkkkkkk...........',
], { k: PICO8[0], b: PICO8[7], s: PICO8[6], f: PICO8[15], g: PICO8[10], e: PICO8[12], w: PICO8[7], r: PICO8[14] });

/** Enemy idle frames keyed by the ENEMIES table id. */
export const ENEMY_FRAMES: Record<string, Anim> = {
  SLIME: slimeFrames,
  GOBLIN: goblinFrames,
  SKELETON: skeletonFrames,
  OGRE_KING: ogreKingFrames,
  WRAITH_LORD: wraithLordFrames,
  DARK_LORD: darkLordFrames,
  ICE_WOLF: iceWolfFrames,
  ICE_BEAR: iceBearFrames,
  FROST_WISP: frostWispFrames,
  YETI: yetiFrames,
  SANDWORM: sandwormFrames,
  SCORPION: scorpionFrames,
  MUMMY: mummyFrames,
  SAND_GOLEM: sandGolemFrames,
  GUARDIAN: guardianFrames,
  ORACLE: oracleFrames,
  PALADIN: paladinFrames,
  SERAPH: seraphFrames,
};

// --- Gear icon sprites (5x5, one identity hue each) -------------------------
const iconMap = (c: string) => ({ k: PICO8[0], c });
export const ICON_SWORD = makeSprite(['...k.', '..kc.', '.kc..', 'kc...', 'c....'], iconMap(PICO8[6]));
export const ICON_WAND = makeSprite(['..k..', '.kck.', '..c..', '.kck.', '..k..'], iconMap(PICO8[13]));
export const ICON_ARMOR = makeSprite(['.kkk.', 'kcckk', 'kcckk', '.kck.', '..k..'], iconMap(PICO8[9]));
export const ICON_NECKLACE = makeSprite(['..k..', '.kck.', 'kcccc', '.kck.', '..k..'], iconMap(PICO8[14]));
export const ICON_CHALICE = makeSprite(['k...k', 'kcccc', '.kck.', '..k..', '.kkk.'], iconMap(PICO8[10]));
export const ICON_BOOTS = makeSprite(['kk...', 'kc...', 'kc...', 'kcccc', 'kkkkk'], iconMap(PICO8[4]));
export const ICON_TOME = makeSprite(['kkkkk', 'kcckc', 'kcckc', 'kcckc', 'kkkkk'], iconMap(PICO8[11]));
export const ICON_EMPTY = makeSprite(['k...k', '.....', '.....', '.....', 'k...k'], iconMap(PICO8[5]));

// --- Room icon sprites (5x5) --------------------------------------------------
const roomIconMap = (c: string) => ({ k: PICO8[0], c });
export const fightIcon = makeSprite(['k...k', '.k.k.', '..k..', '.k.k.', 'k...k'], roomIconMap(PICO8[8]));
export const eliteIcon = makeSprite(['k.k.k', '.kkk.', 'kkkkk', '.kkk.', 'k.k.k'], roomIconMap(PICO8[9]));
export const restIcon = makeSprite(['..k..', '..k..', 'kkkkk', '..k..', '..k..'], roomIconMap(PICO8[11]));
export const lootIcon = makeSprite(['.kkk.', 'kcccc', 'kkkkk', 'kcccc', 'kkkkk'], roomIconMap(PICO8[10]));
export const bossIcon = makeSprite(['k.k.k', 'kkkkk', 'kckck', 'kkkkk', 'kkkkk'], roomIconMap(PICO8[14]));
