// game/art/pixel/ember-gen.ts — generated by tools/intake.mjs from
// tools/in/ember-gen-1.png
// pitch 1px source -> 33x63 cells, 19 colours
// (mean quantization ΔE 16.16), 1 8-connected
// component(s), 0 isolated cell(s) removed. Judge on
// tools/study.html?gen=EMBER_GEN beside the reference crops, the kit's EMBER and
// EMBER_STUDY, and re-run tools/intake.mjs to regenerate.
//
// TODO(intake): attack/hurt/cast/dead and the two other idle frames are
// copies of this master frame until a real pose set is generated and judged.

import type { PixelStudy } from './ember-study';

const MAP: Readonly<Record<string, string>> = {
  o: '#1c1416',
  h: '#4e3b3d',
  H: '#7a5d59',
  i: '#95736f',
  I: '#a7887c',
  s: '#c9c2ba',
  k: '#a77465',
  K: '#c3a28c',
  w: '#e6e5e2',
  q: '#261d21',
  V: '#4e3b42',
  m: '#6a5257',
  M: '#907577',
  c: '#24212c',
  C: '#4d465d',
  p: '#625b70',
  P: '#7e778d',
  l: '#563f3e',
  L: '#997261',
  b: '#b2957a',
  g: '#571d05',
  f: '#e16614',
  F: '#eca351',
  y: '#efd29f',
};

// master frame, 33 columns x 63 rows.
const MASTER: readonly string[] = [
  '............................f.f..',
  '............................fff..',
  '............................fFf..',
  '............................fFFf.',
  '..........................ccffFf.',
  '..........................fcfFFF.',
  '...........cg.............kcFyFFf',
  '............fqg...........lFcyFcc',
  '.......gfffgggfg..........cccFFgc',
  '....g.ggfffffgff..........ccVccc.',
  '....fggqqfffffffql.........kclkc.',
  '....gqfggggfffgfVgq........cclc..',
  '....qffggfffgfgfqfq........ccc...',
  '...gffgffffffVVVqqg........lcc...',
  '...ggffgfffVcVVVqfgg.gg....ccc...',
  'qqggfgVffVVcfffffgffg.Vf...ccc...',
  '.ggggggfgVggfffffffVqgfC...ccc...',
  '.gqVVVgfVfgggffggfffggfg...cc....',
  '..gVgfgVcfgfggggfffffffg...ccc...',
  '.gVVffVVcffgfffffffgffgfg..cc....',
  'gggffgVcggfgggffffFVgfgfg..cc....',
  'qgggfggcfgggffffffyyffVgg..cc....',
  'q.qgfggVcfgfffgffyyyffqf...cm....',
  '...gggVVcqggVVgfcccyfqfg...cg....',
  '...CggVgVgggyVggywcygggf..cgg....',
  '.qqgVVVfgVgVyqgyyyyyM..f..cfg....',
  '..qfgVffVgcVVVfyyyyyy..g..cgl....',
  '..gggfffVgVccVqgyyyyM.....cfc....',
  '....qfgcggggqcVFfccc......ccC....',
  '....gfgqfgggggggqcVf......cc.....',
  '.....qq.gqggcgggFcVg......cc.....',
  '.....ggg..gyyVVfcFcc......cc.....',
  '......qq..cyyFgfgyFcg.....cc.....',
  '..........cyycgffyyyc....cyyg....',
  '.........qyyycgggqKych..cccyg....',
  '.........MyycVgggILLcccckccyg....',
  '.........cyyqcgggcKccykgcccc.....',
  '........gyycgccggVcHcFlccclh.....',
  '.......cccyg.gccccccchc...lg.....',
  '.......cVlcccVcccqfgc....ccg.....',
  '.......chgq.ccccgfcccf...cl......',
  '.......clc.cVggfffKbcc...cc......',
  '.......clc.cggffgfbyyfg..cc......',
  '.......cccccgffffcyyycf..cc......',
  '.......lkyccccfffcccccg..cc......',
  '.......FyVccccVccccVccf..cq......',
  '.......cyc.ccVVVccVVVcc..cq......',
  '...........cVVVCccVVV....cc......',
  '...........VVVVCcccVV...cgh......',
  '..........cccVVccccVc...cgc......',
  '.........cCVccccccVcc...cgc......',
  '.........cccccc.ccccc...cc.......',
  '........clgccc.cclcch...cf.......',
  '.........cgccc..cclgc...cc.......',
  '.........cclcc..cccc....cc.......',
  '.........ccqc...ccVc....ckc......',
  '.........ccc.....cqcc...ckc......',
  '.........ccc....cVlc....cc.......',
  '.........ccc....cqcgc..cql.......',
  '.........ccc....cVllkccClc.......',
  '........ccggc...chcllHc.cc.......',
  '........ccllc....c.cccc.cc.......',
  '.........cccc....................',
];

const TODO_COPY: ReadonlyArray<ReadonlyArray<string>> = [MASTER, MASTER, MASTER];

export const EMBER_GEN: PixelStudy = {
  id: 'EMBER_GEN',
  map: MAP,
  poses: {
    idle: [MASTER, MASTER, MASTER],
    attack: TODO_COPY,
    hurt: TODO_COPY,
    cast: TODO_COPY,
    dead: TODO_COPY,
  },
  feet: { x: 16, y: 63 },
  hit: { x: 14, y: 33 },
  hitSize: { w: 29, h: 25 },
};
