// game/art/pixel/ember-gen2.ts — generated by tools/intake.mjs from
// tools/in/ember-gen-2k.png
// pitch 1px source -> 34x62 cells, 11 colours
// (mean quantization ΔE 14.43), 1 8-connected
// component(s), 2 isolated cell(s) removed. Judge on
// tools/study.html?gen=EMBER_GEN2 beside the reference crops, the kit's EMBER and
// EMBER_STUDY, and re-run tools/intake.mjs to regenerate.
//
// TODO(intake): attack/hurt/cast/dead and the two other idle frames are
// copies of this master frame until a real pose set is generated and judged.

import type { PixelStudy } from './ember-study';

const MAP: Readonly<Record<string, string>> = {
  o: '#1c1416',
  h: '#4e3b3d',
  H: '#7a5d59',
  i: '#95736f',
  I: '#a7887c',
  s: '#c9c2ba',
  k: '#a77465',
  K: '#c3a28c',
  w: '#e6e5e2',
  q: '#261d21',
  V: '#4e3b42',
  m: '#6a5257',
  M: '#907577',
  c: '#24212c',
  C: '#4d465d',
  p: '#625b70',
  P: '#7e778d',
  l: '#563f3e',
  L: '#997261',
  b: '#b2957a',
  g: '#571d05',
  f: '#e16614',
  F: '#eca351',
  y: '#efd29f',
};

// master frame, 34 columns x 62 rows.
const MASTER: readonly string[] = [
  '.............................ff...',
  '.............................FFf..',
  '.............................fFff.',
  '.......ooo..................fFFFf.',
  '.......ofFog...............ffFFff.',
  '........ooFfo..............FFyFFF.',
  '....oofffgffg.gff..........FFyyFFg',
  '....offfFFfggo.ofo........oqFqyqfg',
  '....offffffgggooqo........offfyof.',
  '..ogffffFggoofffffoooo....oggfofo.',
  '.gFFfffFffgqffffffffFFf....gggfoo.',
  '.ffggffggoffFFfFffffgoff....ogfgo.',
  '.foogffgooffffFFfffgfgoo....lqfo..',
  '...ggffogfffgFfFfffgfffo....olgo..',
  '..offfgoffffgfffffggfFFFo...oqo...',
  '..ofgfogggfggfffffffggfff...ffo...',
  '..ffffogfgfgffffffFFgffffo..ogl...',
  'offofgofffgffffffggFFfggfo..ofo...',
  '.ooofgogfggffgfgfooFFgogfg..oqo...',
  '...ffgofgggogffgoqoFfoggfg.ofgo...',
  '...ofgoffgoFgffgwwoyFwg.f..ohgo...',
  '...of..ofgofgffFFwgyFg.....ogo....',
  '....f..fggoFgffFFFFFFFg....ooo....',
  '....o..ooogooofFFyFFFgg....ofo....',
  '.........ffoqfgfyFFFFfg.....fg....',
  '........oo.ooogffoo..g......fo....',
  '...........offFffooo.......ofo....',
  '.........oofqffoffoFo......ogo....',
  '........oyFgfffoFFfof......of.....',
  '........oFFFFffglFhffo.....oo.....',
  '........oFFgFfffgHqfgo.....oo.....',
  '........FFFfffffFlqyfof...oFFo....',
  '.......oFFfogfffFhFloFFooofgyo....',
  '.......FFFooggffFFyogfFfgoloyo....',
  '......oFFf.ogfffyyyFgffoggooyo....',
  '.....ogqqo.offflLyqqgoooqoooo.....',
  '.....oggho..ooooqfooo..oooogo.....',
  '.....ogfg..olggfofofg.....ogo.....',
  '......ofg..gggolqhofgo....ogo.....',
  '.....oofo.ogfflllqqogg....ooo.....',
  '.....oqHh.gfffllllhhfgo...og......',
  '.....olHhooffhllhlolqfo...og......',
  '.....olyFFoholllohllffo...go......',
  '......Fygoohhllhoqhlqfo...fo......',
  '.......oo.qllllloqllqoo...oo......',
  '..........ollllo.hhllho...fo......',
  '..........hllllq.hhllho..ofo......',
  '.........ollllo..ohlll...ogo......',
  '.........ollhh...ohllo...ogo......',
  '........olhhhh...hlhh....olo......',
  '........hllho....hlll....lo.......',
  '.......ooqllh...ohhllo..ogo.......',
  '.......ggfooo...oloooo..ogo.......',
  '.......ggoqg....olgggo..ofo.......',
  '.......oqoqg.....gqglg..lfh.......',
  '.......ogqo......oqloo..oo........',
  '.......olgo......oogqo..gg........',
  '.......ooqo......ogqgqo.og........',
  '.......oglh......lgggfqooo........',
  '......ogffg......llqgggfoo........',
  '......ogqlqo.....hloogqqoo........',
  '......oooloo........ooooo.........',
];

const TODO_COPY: ReadonlyArray<ReadonlyArray<string>> = [MASTER, MASTER, MASTER];

export const EMBER_GEN2: PixelStudy = {
  id: 'EMBER_GEN2',
  map: MAP,
  poses: {
    idle: [MASTER, MASTER, MASTER],
    attack: TODO_COPY,
    hurt: TODO_COPY,
    cast: TODO_COPY,
    dead: TODO_COPY,
  },
  feet: { x: 16, y: 62 },
  hit: { x: 16, y: 32 },
  hitSize: { w: 28, h: 26 },
};
